# Generated by Django 5.2.15 on 2026-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('DailyRate', models.FloatField()),
                ('DistanceFromHome', models.FloatField()),
                ('EmployeeNumber', models.IntegerField()),
                ('MonthlyIncome', models.FloatField()),
                ('MonthlyRate', models.FloatField()),
                ('TotalWorkingYears', models.FloatField()),
                ('YearsAtCompany', models.FloatField()),
                ('YearsInCurrentRole', models.FloatField()),
                ('YearsWithCurrManager', models.FloatField()),
                ('JobRole_Sales_Representative', models.BooleanField()),
                ('OverTime_Yes', models.BooleanField()),
            ],
        ),
    ]
